// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDwIGgZ8RsDybqPzoQQiEh7FqYCmoFGM',
    appId: '1:686138472321:web:5b5a5ee653d0d50e485a80',
    messagingSenderId: '686138472321',
    projectId: 'fir-series-6d61e',
    authDomain: 'fir-series-6d61e.firebaseapp.com',
    storageBucket: 'fir-series-6d61e.appspot.com',
    measurementId: 'G-8EKYZ5WNK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-X4P5mP_Yt4UnRClH8J0sOnNJUlh-IU',
    appId: '1:686138472321:android:09169fce02aa530f485a80',
    messagingSenderId: '686138472321',
    projectId: 'fir-series-6d61e',
    storageBucket: 'fir-series-6d61e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ucHJbKFPpA6XeJxqF0FNV5mXMPLE838',
    appId: '1:686138472321:ios:0be460e9149c2337485a80',
    messagingSenderId: '686138472321',
    projectId: 'fir-series-6d61e',
    storageBucket: 'fir-series-6d61e.appspot.com',
    iosBundleId: 'com.example.rentCarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ucHJbKFPpA6XeJxqF0FNV5mXMPLE838',
    appId: '1:686138472321:ios:07c78859d2aa49b7485a80',
    messagingSenderId: '686138472321',
    projectId: 'fir-series-6d61e',
    storageBucket: 'fir-series-6d61e.appspot.com',
    iosBundleId: 'com.example.rentCarApp.RunnerTests',
  );
}
